accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    
    path('', views.home, name="home"),
    path('login/', views.loginpage, name="login"),
    path('logout/', views.logoutUser, name="logout"),
    path('register/', views.register, name="register"),
    path('order/', views.order, name="order"),
    path('waiting/', views.waiting, name="waiting"),
    path('shipping/', views.shipping, name="shipping"),
    path('successandcancel/', views.successandcancel, name="successandcancel"),
    path('item/', views.item, name="item"),
    path('vegetableandfruit/', views.vegetableandfruit, name="vegetableandfruit"),
    path('productvegetableandfruit/', views.productvegetableandfruit, name="productvegetableandfruit"),
    path('foodanddrink/', views.foodanddrink, name="foodanddrink"),
    path('item/<str:pk>', views.update, name="update"),
    path('delete/<str:pk>', views.delete, name="delete"),
    path('receiveorder/<str:pk>', views.receiveorder, name="receiveorder"),
    path('cancelorder/<str:pk>', views.cancelorder, name="cancelorder"),
    path('confirmorder/<str:pk>', views.confirmorder, name="confirmorder"),
    path('orderdetail/<str:pk>', views.orderdetail, name="orderdetail"),
    
]

api/urls.py
from urllib.parse import urlparse
from django.urls import path
from . import views
from .views import RegisterAPI, LoginAPI
from knox import views as knox_views

urlpatterns = [
    path('',views.getData),
    path('add/',views.addAlluser),
    path('register/', RegisterAPI.as_view(), name='registerapi'),
    path('login/', LoginAPI.as_view(), name='loginapi'),
    path('logout/', knox_views.LogoutView.as_view(), name='logoutapi'),
    path('logoutall/', knox_views.LogoutAllView.as_view(), name='logoutallapi'),
    path('user/', views.get_uesr_data, name='userapi'),
    path('user/<str:pk>/', views.onlyuser, name='onlyuserapi'),
    path('createitem/', views.createitem, name='Productaddapi'),
    path('createorder/', views.createorder, name='Createorderapi'),
    path('item/', views.item, name='Productitemapi'),
    path('order/', views.order, name='orderapi'),
    path('foodanddrink/', views.foodanddrink, name='foodanddrinkapi'),
    path('productvegetableandfruit/', views.productvegetableandfruit, name='productvegetableandfruitapi'),
    path('vegetableandfruit/', views.productvegetableandfruit, name='vegetableandfruitapi'),
]

freshdaydb/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

from .views import ping

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ping/', ping, name="ping"),
    path('', include('accounts.urls')),
    path('api/',include('api.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

accounts/models.py
from asyncio.windows_events import NULL
from itertools import product
from operator import mod
from pydoc import describe
from re import T
from unicodedata import category
from django.db import models
from django.contrib.auth.models import User
from django.forms import ChoiceField

# Head
# Alluser
# Location
# Discount
# Stock
# ProductCategory
# Coupon
# UserPayment
# OrderPayment
# BasketSession
# Shop
# Order
# Product
# BasketItem
# OrderDetail

# Create your models here.
class Alluser(models.Model):
    user = models.OneToOneField(User, null=True,blank = True, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=200, null=True)
    sir_name = models.CharField(max_length=200, null=True)
    phone_number = models.CharField(max_length=200, null=True)
    email = models.CharField(max_length=200, null=True)
    # profile_pic = models.ImageField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)

    def __str__(self):
        return self.first_name

class Location(models.Model):
    alluser_id = models.ForeignKey(
        Alluser, null=True, on_delete=models.SET_NULL)
    landmark = models.CharField(max_length=200,null=True)
    address_number = models.CharField(max_length=200,null=True)
    sub_district = models.CharField(max_length=200,null=True)
    district = models.CharField(max_length=200,null=True)
    city = models.CharField(max_length=200,null=True)
    postal = models.IntegerField(null=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)
    
    def __str__(self):
        return self.landmark

class Discount(models.Model):
    name = models.CharField(max_length=200, null=True, blank=True)
    description = models.CharField(max_length=200, null=True, blank=True)
    discount_percent = models.FloatField(null=True)
    activate = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)
    
    def __str__(self):
        return str(self.id)

# class Stock(models.Model):
#     quanity = models.IntegerField(null=True)
#     created_at = models.DateTimeField(auto_now_add=True, null=True)
#     updated_at = models.DateTimeField(auto_now=True, null=True)
    
#     def __str__(self):
#         return str(self.id)

# class ProductCategory(models.Model):
#     category = [('vegetableandfruit', 'vegetableandfruit'),
#               ('producvegetableandfruit', 'producvegetableandfruit'),
#               ('foodanddrink', 'foodanddrink'),
#               ]
#     name = models.CharField(max_length=200, null=True)
#     created_at = models.DateTimeField(auto_now_add=True, null=True)
#     updated_at = models.DateTimeField(auto_now=True, null=True)
#     product_category = models.CharField(max_length=200, null=True, choices=category)

#     def __str__(self):
#         return self.name

class Coupon(models.Model):
    alluser_id = models.ForeignKey(
        Alluser, null=True, on_delete=models.SET_NULL)
    name = models.CharField(max_length=200, null=True)
    description = models.CharField(max_length=200, null=True)
    discount = models.FloatField(null=True)
    expiration_date = models.DateTimeField(null=False)  
    activate = models.BooleanField(default=False)
    date_created = models.DateTimeField(auto_now_add=True, null=True)  
    updated_at = models.DateTimeField(auto_now=True, null=True) 
    def __str__(self):
        return self.name

class UserPayment(models.Model):
    alluser_id = models.ForeignKey(
        Alluser, null=True, on_delete=models.SET_NULL)
    provider = models.CharField(max_length=200, null=True)
    card_number = models.CharField(max_length=200, null=True)
    expiration_date = models.DateTimeField(null=False)
    
    def __str__(self):
        return self.provider
    
class OrderPayment(models.Model):
    user_payment_id = models.ForeignKey(
        UserPayment, null=True, on_delete=models.SET_NULL)
    status = models.CharField(max_length=200, null=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)  
    updated_at = models.DateTimeField(auto_now=True, null=True) 
    
    def __str__(self):
        return str(self.id)
    
class BasketSession(models.Model):
    alluser_id = models.ForeignKey(
        Alluser, null=True, on_delete=models.SET_NULL)
    total = models.FloatField(null=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)  
    updated_at = models.DateTimeField(auto_now=True, null=True) 
    
    def __str__(self):
        return str(self.id)
    

    
class Order(models.Model):
    status = [('waiting', 'waiting'),
              ('shipping', 'shipping'),
              ('success', 'success'),
              ('cancel', 'cancel'),
              ]
    alluser_id = models.ForeignKey(
        Alluser, null=True, on_delete=models.SET_NULL)
    amount = models.IntegerField(null=True)
    order_payment_id = models.ForeignKey(
        OrderPayment, null=True, on_delete=models.SET_NULL)
    coupon_id = models.ForeignKey(
        Coupon, null=True, on_delete=models.SET_NULL)
    location_id = models.ForeignKey(
        Location, null=True, on_delete=models.SET_NULL)

    date_created = models.DateTimeField(auto_now_add=True, null=True)  
    updated_at = models.DateTimeField(auto_now=True, null=True) 
    order_status = models.CharField(max_length=200, null=True, choices=status)
    def __str__(self):
        return str(self.id)


class Product(models.Model):
    category = [('vegetableandfruit', 'vegetableandfruit'),
              ('productvegetableandfruit', 'productvegetableandfruit'),
              ('foodanddrink', 'foodanddrink'),
              ]
    name = models.CharField(max_length=200, null=True)
    description = models.CharField(max_length=200, null=True, blank=True)
    price = models.FloatField(null=True)
    shop_id = models.ForeignKey(
        Alluser, null=True, on_delete=models.SET_NULL)
    discount_id = models.ForeignKey(
        Discount, null=True , on_delete=models.SET_NULL)
    # stock_id = models.ForeignKey(
    #     Stock, null=True, on_delete=models.SET_NULL)
    # product_category_id = models.ManyToManyField(ProductCategory)
    product_image = models.ImageField(null=True, blank=True)
    quanity = models.IntegerField(null=True)
    type = models.CharField(max_length=200, null=True, choices=category)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)

    def __str__(self):
        return self.name
    
class BasketItem(models.Model):
    basket_session_id = models.ForeignKey(
        BasketSession, null=True, on_delete=models.SET_NULL)
    product_id = models.ForeignKey(
        Product, null=True, on_delete=models.SET_NULL)
    quanity = models.IntegerField(null=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)  
    updated_at = models.DateTimeField(auto_now=True, null=True) 
    
    def __str__(self):
        return str(self.id)
    
class OrderDetail(models.Model):
    order_id = models.ForeignKey(
        Order, null=True, on_delete=models.SET_NULL)
    product_id = models.ForeignKey(
        Product, null=True, on_delete=models.SET_NULL)
    price = models.FloatField(null=True)
    quanity = models.IntegerField(null=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)  
    updated_at = models.DateTimeField(auto_now=True, null=True) 
    
    def __str__(self):
        return str(self.id)


# class CreateItem(models.Model):
#     pass

accounts/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import Order, Product

class OrderForm(ModelForm):
    class Meta:
       model = Order
       fields = '__all__'

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        
class ItemForm(ModelForm):
    class Meta:
       model = Product
       fields = '__all__'

accounts/templates/accounts/delete_item.html
{% load static %}
{% block content %} 



            <button type="submit" class="form-control btn rounded submit mx-auto" data-bs-toggle="modal" data-bs-target="#exampleModal{{product.id}}">
              <div class="img" style="width:3rem;">
                <img src="\static\images\trash.png" class="img-fluid" alt="Responsive image">
                </div>
            </button>
            
   
    
    <!-- Modal -->
    <div class="modal fade" id="exampleModal{{product.id}}" tabindex="-1" aria-labelledby="exampleModalLabel{{product.id}}" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel{{product.id}}">Delete</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <form action="{% url 'delete' product.id %}" method="POST">
          <div class="modal-body">
            <div class="mb-3">
                <label class="label" for="name">Are you sure delete {{product.name}}(Id : {{product.id}})</label>
              </div>
              {% csrf_token %}
          </div>
          <div class="modal-footer">
            <div class="form-group">
              <input type="submit" class="btn btn-danger" value="Delete!" name="Delete!">
          </div>
          {% comment %} <div class="col-2">
            <button type="submit" class="form-control btn btn-success rounded submit px-3" href="{% url "item/" %}">
                Cancel
            </button>
          </div> {% endcomment %}
            
          </form>
          {% comment %} <a href="{% url "item/" %}">
            Cancel
          </a> {% endcomment %}

        </div>
      </div>
    </div>

{% endblock %}

accounts/templates/accounts/item_foodanddrink.html
{% extends 'accounts/main.html' %} 
{% load static %}
{% block content %}

<section class="home-section vh-100">
  {% comment %} Confirm Order {% endcomment %}
  <div class="row g-0 rounded ms-3" style="padding-right:16px">
    
  
      <div class="col-lg-7 col-xl-12 pe-lg-2 mb-3">
        <div class="card h-lg-100 ">
          <div class="card-header d-flex flex-between-center bg-light py-2 ">
            <div class="container">
              <div class="row">
                <h6 class="col mb-0 d-flex align-self-center ">Manage item</h6>
                
                <div class="col-3" >
                  {% include "accounts/create_item.html" %}
                </div>
                {% comment %} <div class="col-3">
                  <button type="submit" class="form-control btn btn-danger rounded submit px-3 " disabled >
                   - Delete Item
                  </button>
                  </div>
                <div class="col-2">
                    <button type="submit" class="form-control btn btn-success rounded submit px-3">
                      Status:ON
                    </button>
                    </div>
                <div class="col-2">
                  <button type="submit" class="form-control btn btn-danger rounded submit px-3">
                    Status:OF
                  </button>
                </div> {% endcomment %}
              </div>
              </div>
          </div>
          <div id="includedContent"></div>
          <div class="card-body p-0">
            <div class="table-responsive scrollbar">
              <table
                class="table table-dashboard mb-0 table-borderless fs--1 border-200"
              >
                <thead class="table">
                  <tr class="text-900">
                    {% comment %} <th>checkbox</th> {% endcomment %}
                    <th>image</th>
                    <th>name</th>
                    <th>type</th>
                    <th>price</th>
                    <th>status</th>
                    <th>Quantity</th>
                    
                  </tr>
                </thead>
                {% for product in products %}
                <tbody>
                  <tr class="border-bottom border-200">
                    {% comment %} <td>
                      <div class="d-flex align-items-center position-relative">
                        <div class="flex-1 ms-3">
                          <input type="checkbox"  onchange="document.getElementById('grabaperaus').disable = !this.checked;" >
                          <input class="form-check-input"  type="checkbox" value="" id="flexCheckDefault">
                          
                        </div>
                      </div>
                    </td> {% endcomment %}
                    <td class="align-middle pe-card">
                      <div class="d-flex align-items-center position-relative">
                        <div class="flex-1 ms-3">
                          <div class="img" style="width:6rem;">
                            <img src="\static\images\{{product.product_image}}" class="img-fluid" alt="Responsive image">
                            </div>
                         
                        </div>
                      </div>
                    </td>
                    <td class="align-middle pe-card">
                      <div class="d-flex align-items-center position-relative">
                        <div class="flex-1 ms-3">
                          <h6 class="mb-1 fw-semi-bold">
                            <a class="text-dark stretched-link" href="#"
                              >{{product.name}}</a
                            >
                          </h6>
                        </div>
                      </div>
                    </td>
                    <td class="align-middle pe-card">
                      <div class="d-flex align-items-center position-relative">
                        <div class="flex-1 ms-3">
                          <h6 class="mb-1 fw-semi-bold">
                            <a class="text-dark stretched-link" href="#">
                              {{product.type}}
                            </a>
                          </h6>
                        </div>
                      </div>
                    </td>
                    <td class="align-middle pe-card">
                      <div class="d-flex align-items-center position-relative">
                        <div class="flex-1 ms-3">
                          <h6 class="mb-1 fw-semi-bold">
                            <a class="text-dark stretched-link" href="#"
                              >{{product.price}}฿</a
                            >
                          </h6>
                        </div>
                      </div>
                    </td>
                    <td class="align-middle pe-card">
                      <div class="d-flex align-items-center position-relative">
                        <div class="flex-1 ms-3">
                          <h6 class="mb-1 fw-semi-bold">
                              <div class="form-check form-switch">
                                <input class="form-check-input" type="checkbox" id="flexSwitchCheckDefault">
                                <label class="form-check-label" for="flexSwitchCheckDefault"></label>
                              </div>
                              
                        </div>
                      </div>
                    </td>
                    <td class="align-middle pe-card">
                      <div class="d-flex align-items-center position-relative">
                        <div class="flex-1 ms-3">
                          <h6 class="mb-1 fw-semi-bold">
                            <a class="text-dark stretched-link" href="#"
                              >{{product.quanity}}</a
                            >
                          </h6>
                        </div>
                      </div>
                    </td>
                    
                    <td class="align-middle pe-card">
                      {% comment %} <div class="d-flex align-items-center position-relative">
                        <div class="flex-1 ms-3">
                          <h6 class="mb-1 fw-semi-bold">
                            <a class="text-dark stretched-link" href="#">
                              <img src="{% static 'images\edit.png' %}" class="w-100 h-100">
                            </a>
                          </h6>
                        </div>
                      </div> {% endcomment %}
                      {% include "accounts/update_item.html" %}
                    </td>
                    
                    <td class="align-middle pe-card">
                      <div class="d-flex align-items-center position-relative">
                        <div class="flex-1 ms-3">
                          <h6 class="mb-1 fw-semi-bold">
                            {% include "accounts/delete_item.html" %}
                          </h6>
                        </div>
                      </div>
                    </td>
                      
                  </tr>
                </tbody>
                {% endfor %}
              </table>
            </div>
          </div>
          <div class="card-footer bg-light py-2">
            <div class="row flex-between-center">
              <div class="col-auto">
                <select class="form-select form-select-sm">
                  <option>Last 7 days</option>
                  <option>Last Month</option>
                  <option>Last Year</option>
                </select>
              </div>
              <div class="col-auto">
                <a class="btn btn-sm btn-falcon-default" href="#!">View All</a>
              </div>
            </div>
          </div>
        </div>
      </div>
  </section>
{% endblock content %}

accounts/templates/accounts/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    {% include "accounts/head_part.html" %}

    <title>login</title>

    <link
      rel="stylesheet"
      type="text/css"
      href="{% static '/css/style.css' %}"
    />

    <link
      href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap"
      rel="stylesheet"
    />

  </head>

  <body>
    <section class="ftco-section">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-md-12 col-lg-10">
            <div class="wrap d-md-flex">
              <div
                class="img"
                style="background-image: url({% static 'images\cabbage.png' %})"
              >
                <!-- <img src="{% static 'images/bg-1.jpg' %}"> -->
              </div>
              <div class="login-wrap p-4 p-md-5">
                <div class="d-flex">
                  <div class="w-100">
                    <h3 class="mb-4">Sign In</h3>
                  </div>
                  <div class="w-100">
                    <p class="social-media d-flex justify-content-end">
                      <a
                        href="#"
                        class="social-icon d-flex align-items-center justify-content-center"
                        ><span class="fa fa-facebook"></span
                      ></a>
                      <a
                        href="#"
                        class="social-icon d-flex align-items-center justify-content-center"
                        ><span class="fa fa-twitter"></span
                      ></a>
                    </p>
                  </div>
                </div>
                <form method="POST" action="#" class="signin-form">
                  {% csrf_token %}
                  <div class="form-group mb-3">
                    <label class="label" for="name">Username</label>
                    <input
                      type="text"
                      class="form-control"
                      placeholder="username"
                      name="username"
                      required
                    />
                  </div>
                  <div class="form-group mb-3">
                    <label class="label" for="password">Password</label>
                    <input
                      type="password"
                      class="form-control"
                      placeholder="password"
                      name="password"
                      required
                    />
                  </div>
                  <div class="form-group">
                    <input class="form-control btn btn-primary rounded submit px-3" type="submit" value="Sign In">
                  </div>
                  <div class="form-group d-md-flex">
                    <div class="w-50 text-left">
                      <label class="checkbox-wrap checkbox-primary mb-0"
                        >Remember Me
                        <input type="checkbox" checked />
                        <span class="checkmark"></span>
                      </label>
                    </div>
                    <div class="w-50 text-md-right">
                      <a href="#">Forgot Password</a>
                    </div>
                  </div>
                </form>
                {% for message in messages %}
                  <p id="message"> {{message}} <p>
                {% endfor %}
                <p class="text-center">
                  Not a member? <a data-toggle="tab" href="{% url 'register' %}">Sign Up</a>
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </body>
</html>

accounts/templates/accounts/order_detail.html
{% load static %}
{% block content %}


<button type="submit" class="form-control btn rounded submit px-3" data-bs-toggle="modal" data-bs-target="#orderdetail{{order.id}}">
    Veiw Detail
  </button>


  <div class="modal fade" id="orderdetail{{order.id}}" tabindex="-1" aria-labelledby="detailorderLabel{{order.id}}" aria-hidden="true">
    <div class="modal-dialog modal-xl">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="detailorderLabel{{order.id}}">Veiw Detail Order : {{order.id}}</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <!--body-->
        <form action="{% url 'orderdetail' order.id %}" method="POST">
            <div class="modal-body">
                <div class="container-fluid">
                <div class="row">
                    <div class="col-md-4"> 
                    </div>
                    <div class="col-md-4 ms-auto">{{order.id}}</div>
                </div>
                <div class="row">
                    <div class="col-md-3 ms-auto"></div>
                    <div class="col-md-2 ms-auto">{{order.alluser_id.location}}</div>
                </div>
                <div class="row">
            <div class="col-md-6 ms-auto">{{order.amount}}</div>
                </div>
                <div class="row">
                    <div class="col-sm-9">
                    Level 1: .col-sm-9
                    <div class="row">
                        <div class="col-8 col-sm-6">
                        Level 2: .col-8 .col-sm-6
                        </div>
                        <div class="col-4 col-sm-6">
                        Level 2: .col-4 .col-sm-6
                        </div>
                    </div>
                    </div>
                </div>
                </div>
            </div>
            </div>
        </form>
    </div>
  </div>



{% endblock content %} 

accounts/templates/accounts/update_item.html
{% load static %}
{% block content %}

<div class="d-flex align-items-center position-relative">
  <div class="flex-1 ms-3">
    <h6 class="mb-1 fw-semi-bold">
      <a class="text-dark stretched-link" href="#updateitem{{product.id}}" data-bs-toggle="modal" data-bs-target="#updateitem{{product.id}}">
        <img src="{% static 'images\edit.png' %}" class="w-100 h-100">
      </a>
    </h6>
  </div>
</div>
{% comment %} 
<button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#updateitem">
  + Create Item
 </button> {% endcomment %}



<!-- Modal -->
<div class="modal fade" id="updateitem{{product.id}}" tabindex="-1" aria-labelledby="updateitem" aria-hidden="true">
<div class="modal-dialog">
<div class="modal-content">
<div class="modal-header">
 <h5 class="modal-title" id="updateitem">Edit Item</h5>
 <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
</div>
<!--body-->
<form action="/item/{{product.id}}" enctype="multipart/form-data" method="POST">
  {% csrf_token %}
  <div class="modal-body">
      <table class="table">
        <thead>
          <tr>
            <th scope="col"></th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th scope="row">
              <div class="form-group mb-3">
                <label class="label" for="name">id</label>
              </div>
            </th>
            <td>
              {{product.id}}
            </td>
          </tr>
          <tr>
            <th scope="row">
              <div class="form-group mb-3">
                <label class="label" for="name">Name</label>
              </div>
            </th>
            <td>
              <input type="text" class="form-control" value="{{product.name}}" name="name" required>
            </td>
          </tr>
          <tr>
            <th scope="row">
              <div class="form-group mb-3">
                <label class="label" for="name">Description</label>
              </div>
            </th>
            <td>
              <input type="text" class="form-control" value="{{product.description}}" name="description" required>
            </td>
          </tr>
          <tr>
            <th scope="row">
              <div class="form-group mb-3">
                <label class="label" for="name">Price</label>
              </div>
            </th>
            <td>
              <input type="text" class="form-control" value="{{product.price}}" name="price" required>
            </td>
          </tr>
          <!-- <tr>
            <th scope="row">
              <div class="form-group mb-3">
                <label class="label" for="name">Shop Id</label>
              </div>
            </th>
            <td>
              <input type="text" class="form-control" value="{{product.shop_id}}" name="shop_id" required disabled>
            </td>
          </tr> -->
          <tr>
            <th scope="row">
              <div class="form-group mb-3">
                <label class="label" for="name">Discount Id</label>
              </div>
            </th>
            <td>
              <select class="form-select" aria-label="Default select example" name="discount_id" id="id_discount_id" required>
                <option value="" selected>Open this select menu</option>
                {% for discount in discount %}
                  <option value={{discount.id}}>{{discount.name}}</option>
                {% endfor %}
              </select>
            </td>
          </tr>
          <tr>
            <th scope="row">
              <div class="form-group mb-3">
                <label class="label" for="name">Quanity</label>
              </div>
            </th>
            <td>
              <input type="text" class="form-control" value="{{product.quanity}}" name="quanity" required>
            </td>
          </tr>
          <tr>
            <th scope="row">
              <div class="form-group mb-3">
                <label class="label" for="name">Product Image</label>
              </div>
            </th>
            <td>
              <input type="file" name="product_image" accept="image/*" id="id_product_image">
            </td>
          </tr>
          <tr>
            <th scope="row">
              <div class="form-group mb-3">
                <label class="label" for="name">Type</label>
              </div>
            </th>
            <td>
              <select class="form-select" aria-label="Default select example" name="type">
                <option selected>Open this select menu</option>
                  <option value="vegetableandfruit">vegetableandfruit</option>
                  <option value="producvegetableandfruit">producvegetableandfruit</option>
                  <option value="foodanddrink">foodanddrink</option>
              </select>
            </td>
          </tr>
        </tbody>
      </table>
  </div>
  <div class="modal-footer">
    <div class="form-group">
      <input type="submit"  class="btn btn-success" value="Create!" name="Create!">
    </div>
  </div>
</form>
</div>
</div>
</div>


{% endblock content %}